### ISSUE TITLE
Support images in the Card icon prop type

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/components#50] opened 2023-02-01 18:01 UTC
Images are already rendered correctly but the types need to be updated.

For reference: Images will only render correctly on Mintlify if the file paths are absolute. Relative file paths are not resolved correctly in production. We are working on that MDX parsing problem in the `mint` repo.

**Comment by hanywang2** [comment] 2023-02-08 07:08
@tobias-mintlify is this a duplicate of #57

**Comment by tobias-mintlify** [comment] 2023-02-08 19:00
Reopening, this is a separate issue to allow an image as an _icon_. This issue is super small and is only about updating the type definition of the component.

#57 is about allowing a big image at the top of the card.

**Comment by sboy99** [comment] 2023-02-09 02:42
@tobias-mintlify correct me if I'm wrong. In this updation the icon will accept a href of an image. And the card component will conditionally check is it a image(string) or a svg, right, and based of the condition it will render img and svg respectively.

**Comment by tobias-mintlify** [comment] 2023-02-09 04:19
Yes exactly. String input gets passed to the image `src` property. SVGs will still be passed as components.

**Comment by sboy99** [comment] 2023-02-09 05:01
Then excited to contribute. Assign me, I will give it a try 😸

**Comment by sboy99** [comment] 2023-02-09 05:51
![Screenshot from 2023-02-09 11-19-22](https://user-images.githubusercontent.com/86586277/217729137-8f2dc461-e12e-43fb-bc58-cf9ab3612807.png)

Is it looking good? or it need some modification. If so mention please.

**Comment by sboy99** [comment] 2023-02-09 05:54
![Screenshot from 2023-02-09 11-23-55](https://user-images.githubusercontent.com/86586277/217729834-3f3ce4af-4b06-4a3d-818d-33b8efa09a0d.png)

How can I update this so that icon prop accepts a string as well ??

**Comment by tobias-mintlify** [comment] 2023-02-09 06:54
That's looking good. If you update the [type definition of the component](https://github.com/mintlify/components/blob/main/src/Card.tsx#L13) Storybook should automatically start accepting strings too. You can try something like `icon?: string | ReactNode`.

**Comment by sboy99** [comment] 2023-02-09 08:37
> That's looking good. If you update the [type definition of the component](https://github.com/mintlify/components/blob/main/src/Card.tsx#L13) Storybook should automatically start accepting strings too. You can try something like `icon?: string | ReactNode`.

This is happening although I specified `string | ReactNode`
![Screenshot from 2023-02-09 14-03-41](https://user-images.githubusercontent.com/86586277/217759262-52c2a7e4-20ec-4f8e-84af-7b6ba24402a7.png)

Possible reason is ReactNode has string property as literal type
![Screenshot from 2023-02-09 14-04-19](https://user-images.githubusercontent.com/86586277/217759579-b9d8dbac-9b7a-4f24-96b3-ec0163e5817e.png)

**Comment by sboy99** [comment] 2023-02-09 09:02
Its working if we pass a JSON string
![Screenshot from 2023-02-09 14-25-13](https://user-images.githubusercontent.com/86586277/217765596-78c890fa-f73b-45f8-b0ce-3a998072d9a6.png)

**Closed** 2023-02-10 16:50 UTC
